grow buffer on overflow
GITAI/influxdb-cpp-rest pull request #9
Opened 2021-12-20 03:29 UTC by peroxyacyl

gzipバッファが足りなくなる問題を修正

2021-12-20 06:23 UTC, garaemon requested changes

2021-12-20 06:23 UTC, garaemon commented on src/influxdb-cpp-rest/influxdb2_simple_async_api.cpp
> +                            size_t csize = 0;
size_t -> intとしたいです

2021-12-20 06:23 UTC, garaemon commented on src/influxdb-cpp-rest/influxdb2_simple_async_api.cpp
> +                              auto got = c->compress(
const追加できます?

2021-12-20 06:23 UTC, garaemon commented on src/influxdb-cpp-rest/influxdb2_simple_async_api.cpp
> +                                  reinterpret_cast<const uint8_t*>(w->data()) + processed,
足し引きがややこしいので、一旦別変数に入れておくのはどうでしょうか?

2021-12-20 06:23 UTC, garaemon commented on src/influxdb-cpp-rest/influxdb2_simple_async_api.cpp
> +                              csize += got;
これって、際限なくバッファは大きくなっていくんでしょうか? なんかしらの最大値を設定しておいてもよいのかなと思いました

2021-12-21 10:19 UTC, peroxyacyl commented on src/influxdb-cpp-rest/influxdb2_simple_async_api.cpp
> +                            size_t csize = 0;
参照渡ししていない範囲でintとしました

2021-12-21 10:19 UTC, peroxyacyl commented on src/influxdb-cpp-rest/influxdb2_simple_async_api.cpp
> +                              auto got = c->compress(
追加しました

2021-12-21 10:20 UTC, peroxyacyl commented on src/influxdb-cpp-rest/influxdb2_simple_async_api.cpp
> +                                  reinterpret_cast<const uint8_t*>(w->data()) + processed,
変数を整理しました (足し引きは残っていますが)

2021-12-21 10:20 UTC, peroxyacyl commented on src/influxdb-cpp-rest/influxdb2_simple_async_api.cpp
> +                              csize += got;
16倍に設定しました

2021-12-22 02:00 UTC, garaemon approved these changes

2021-12-22 09:33 UTC, merged